### ISSUE TITLE
PCL Reference Assemblies not installed

### ISSUE THREAD

**Issue by wolli-lenzen** [mono/docker#1]
Build of Mono-Project fails with error:

 /usr/lib/mono/4.5/Microsoft.Common.targets: error : PCL Reference Assemblies not installed.

As I understood, ther had been an issue with PCL using xbuild but that should have been resolved:
https://github.com/mono/mono/commit/c4667496bf3a82b91173c07a761d1dcbf935edf9

Any idea?

**Comment by akoeplinger** [comment]
You need to install the `referenceassemblies-pcl` package via apt to build PCL assemblies.

We'll preinstall that package on the next release, keeping this open for tracking.

**Comment by andmos** [comment]
Any news here? Would like to use the official backage rather than my own :+1:

**Comment by akoeplinger** [comment]
@andmos you can just run apt-get install referenceassemblies-pcl in your Dockerfile to get the assemblies. We'll preinstall them on the Mono 4.4 image.

**Comment by andmos** [comment]
Preinstall would be nice!

**Comment by OtherCrashOverride** [comment]
> You need to install the referenceassemblies-pcl package via apt to build PCL assemblies.

Can you please provide information for manually accomplishing this? This is required for armv8 where none of the Mono packages are available (yet) through apt.

**Comment by akoeplinger** [comment]
@OtherCrashOverride in that case you should be able to install the package by manually downloading the .deb and installing it (assuming the Xamarin apt repo is configured) since the package doesn't contain arch specific files:

```
apt-get download referenceassemblies-pcl
dpkg --force-all -i <name of .deb file>
```

**Comment by OtherCrashOverride** [comment]
> since the package doesn't contain arch specific files:
It does however contain hard coded paths to usr/lib.

It would be much easier if there was simply an armv8 arch added to the Xamarin repo.  Is this planned?

**Comment by akoeplinger** [comment]
> It does however contain hard coded paths to usr/lib.

Yeah, but you can just move it wherever you want if you like.

> It would be much easier if there was simply an armv8 arch added to the Xamarin repo. Is this planned?

Adding AArch64 packages (which I guess is what you want when you say armv8) is planned yes. Stay tuned :)

**Comment by OtherCrashOverride** [comment]
Thanks.  I don't mind doing the .deb extraction in the interim.  Its reassuring to know the AArch64 packages are planned and deb extraction is not meant to be a long term solution.
