### ISSUE TITLE
Dockerfile with enabled LLVM

### ISSUE THREAD

**Issue by Kelindar** [mono/docker#10]
Would it be possible to have dockerfiles with LLVM enabled as well? This would be extremely valuable for us, since we benefit from LLVM optimisations with mono.

**Comment by Kelindar** [comment]
So this is what I've came up with yesterday to accomplish this. This takes a while to build, a bit more than one hour but works. The only downside is that the image is about 1GB size, any thoughts on how to reduce it further?

```bash
FROM debian:wheezy
MAINTAINER Roman Atachiants "roman@misakai.com"

# The versions (github branches) that should be pulled and compiled
ENV LLVM_VERSION=mono-3.4.0
ENV MONO_VERSION=mono-3.12.0.76

# The dependencies needed for the compilation process, they will be deleted once the docker image is baked
ENV DEPENDENCIES="curl git autoconf libtool automake build-essential mono-devel gettext python"
WORKDIR /deploy

RUN apt-get update \
	&& apt-get install -y $DEPENDENCIES \
	&& rm -rf /var/lib/apt/lists/* \
	&& apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
	&& git clone git://github.com/mono/llvm.git --branch $LLVM_VERSION \
	&& cd /deploy/llvm \
	&& ./configure --enable-optimized --enable-targets="x86 x86_64" \
	&& make \
	&& make install \
	&& cd /deploy \
	&& git clone git://github.com/mono/mono --branch $MONO_VERSION  \
	&& cd /deploy/mono \
	&& bash ./autogen.sh --enable-llvm=yes \
	&& make get-monolite-latest \
	&& make \
	&& make install \
	&& apt-get remove -y --purge $DEPENDENCIES \
	&& rm -rf /deploy \
	&& mkdir /app

WORKDIR /app
```

**Comment by akoeplinger** [comment]
You don't need to install `mono-devel` since you're using monolite to compile Mono.

I'll keep this open as a suggestion, but afaik we don't have plans to publish an llvm-enabled Docker image for now.

**Comment by kevfromireland** [comment]
@akoeplinger : Could you elaborate a little on why there are no plans to publish `llvm` enabled Docker images?

**Comment by akoeplinger** [comment]
@kevfromireland the main reason is that the Debian packages this Docker image builds upon (i.e. the official mono-project.com packages) don't have llvm enabled. We'd need to enable it there first.

**Comment by kevfromireland** [comment]
Thanks for the explanation @akoeplinger . Any reason not to enable LLVM on the upstream packages?

**Comment by akoeplinger** [comment]
@kevfromireland because it needs the Mono llvm fork which is a problem for distribution packages, which our packages are based on.

**Comment by kevfromireland** [comment]
Makes sense. So this is unlikely to happen unless Xamarin or some third-party start building this all from source and publishing those packages to a repo and building a docker images from that repo?

**Comment by akoeplinger** [comment]
Yes. We might be able to use stock LLVM in the future (http://tirania.org/blog/archive/2015/Sep-02.html) which should make this easier, but it's not on the radar right now.

Btw. this Docker image is maintained by Xamarin if that wasn't clear.

**Comment by ingojaeckel** [comment]
@akoeplinger  is there a reason Xamarin / the community did not follow the steps on http://www.mono-project.com/docs/advanced/mono-llvm/ yet to build a Docker image that provides mono with LLVM enabled?

**Comment by ingojaeckel** [comment]
Has somebody experience with using this Docker image: neoeinstein/mono-llvm?

@Kelindar @akoeplinger @kevfromireland

**Comment by akoeplinger** [comment]
This is now available in our official image since Linux packages ship with our LLVM fork now (you might need to install the `mono-llvm-support` package):

```shell
$ mono --aot --llvm test.exe
Mono Ahead of Time compiler - compiling assembly /test.exe
AOTID 0CFB3C8B-1BDC-4C68-43B4-D19A21F23295
Executing opt: "/usr/lib/mono/llvm/bin/opt" -f -O2 -disable-tail-calls -o "mono_aot_llOyEG/temp.opt.bc" "mono_aot_llOyEG/temp.bc"
Executing llc: "/usr/lib/mono/llvm/bin/llc"  -march=x86-64 -mattr=sse4.1 -asm-verbose=false -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=mono_aot_test_eh_frame -disable-tail-calls -no-x86-call-frame-opt -relocation-model=pic -filetype=obj -o "mono_aot_llOyEG/temp-llvm.o" "mono_aot_llOyEG/temp.opt.bc"
Code: 0(0%) Info: 6(0%) Ex Info: 10(1%) Unwind Info: 0(0%) Class Info: 30(3%) PLT: 40(4%) GOT Info: 595(69%) Offsets: 170(19%) GOT: 232
Compiled: 2/2 (100%), LLVM: 2 (100%), No GOT slots: 1 (50%), Direct calls: 0 (100%)
Executing the native assembler: "as" --64  -o /tmp/mono_aot_hTyjBV.o /tmp/mono_aot_hTyjBV
Executing the native linker: "ld"  -shared -o /test.exe.so.tmp "mono_aot_llOyEG/temp-llvm.o" /tmp/mono_aot_hTyjBV.o
JIT time: 1 ms, Generation time: 46 ms, Assembly+Link time: 10 ms.

$ file test.exe.so
test.exe.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

Enjoy :)

**Comment by kevfromireland** [comment]
Awesome!
