### ISSUE TITLE
Update image for TLS/SSL issues

### ISSUE THREAD

**Issue by ewindisch** [mono/docker#11]
We would like to see the Docker images for mono updated accordingly for the SKIP-TLS, FREAK, and SSL v2 fallback reports per the following oss-sec thread: http://seclists.org/oss-sec/2015/q1/869

**Comment by akoeplinger** [comment]
The images were updated to include those fixes a while ago in https://github.com/mono/docker/commit/adc7a3ec47f7d590f75a4dec0203a2103daf8db0.
