### ISSUE TITLE
mono-service missing

### ISSUE THREAD

**Issue by tbehrsin** [mono/docker#13]
mono-service appears to be missing from at least the latest image. Is it possible to add it?

**Comment by akoeplinger** [comment]
We don't have plans to add mono-service to the base image right now, but you can add the `mono-4.0-service` package via apt in your own Dockerfile.

**Comment by tekhedd** [comment]
This is an issue, since signal handling in C# is, well... 

Obviously I can hack it in, but this means updating the derived Dockerfile to the correct repo subdirectory with each mono release. :( Really no chance of adding this? He asked without hope...
