### ISSUE TITLE
4.0.2?

### ISSUE THREAD

**Issue by johnnonolan** [mono/docker#14]
Wanted to play with 4.0.2 but it's not here. Is it not stable to go in docker?

**Comment by xelibrion** [comment]
+1, would be great to have the image for 4.0.2

**Comment by akoeplinger** [comment]
@directhex who is maintaining this repo just told me he is too busy right now to update the dockerfiles to 4.0.2, but will happily accept a PR if someone else gets to it.

**Comment by akoeplinger** [comment]
4.0.5.1 is now available. We didn't publish 4.0.2 but in the future minor versions will be published too.
