### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by quaker1** [mono/docker#15]
I want to use [Sourcegraph](https://sourcegraph.com) for docker code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/mono/docker. (It should only take 30 seconds.)

Thank you!

**Comment by akoeplinger** [comment]
I wonder what use case you have for Sourcegraph in this repo? The Dockerfiles are pretty short and self-contained.

**Comment by akoeplinger** [comment]
Closing, as I don't think Sourcegraph provides value here. Feel free to reopen if you think otherwise.
