### ISSUE TITLE
binfmt_misc Error

### ISSUE THREAD

**Issue by CrashyBang** [mono/docker#21]
Whenever I build one of the mono docker containers I get the following error, is this important will it cause any problems down the track?

```bash
update-binfmts: warning: /usr/share/binfmts/cli: no executable /usr/bin/cli found, but continuing anyway as you request
mount: block device binfmt_misc is write-protected, mounting read-only
mount: cannot mount block device binfmt_misc read-only
update-binfmts: warning: Couldn't mount the binfmt_misc filesystem on /proc/sys/fs/binfmt_misc.
```

Cheers,
Otis.

**Comment by akoeplinger** [comment]
I think you can ignore it if you don't use the binfmt detection (i.e. invoking your app with `mono ./app.exe` instead of `./app.exe`.

AFAIK `/usr/bin/cli` should be set up by the debian packages, not sure why it's not happening here. @directhex ?

**Comment by CrashyBang** [comment]
Hey @akoeplinger,

That works for me anyway I have a script that runs the compile so I will just update it to avoid `/`.

Let me know if I can do anything more to help.

Cheers,
Otis.

**Comment by directhex** [comment]
Seems to be a Docker-specific issue, I wouldn't worry about it if you don't plan on using ./foo.exe (which is disrecommended by the Mono app deployment guidelines anyway)

**Comment by CrashyBang** [comment]
Awesome @directhex thanks for clearing that up for me :).

:+1:
