### ISSUE TITLE
Update the docker hub  latest tag 

### ISSUE THREAD

**Issue by naveensrinivasan** [mono/docker#23]
When I use `docker pull mono` it still refer's to 

>root@2530ef213bdb:/# mono --version
>Mono JIT compiler version 4.0.4 (Stable 4.0.4.1/5ab4c0d Tue Aug 25 23:11:51 UTC 2015)
>Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
  >      TLS:           __thread
    >    SIGSEGV:       altstack
      >  Notifications: epoll
      > Architecture:  amd64
      >  Disabled:      none
       > Misc:          softdebug 
       > LLVM:          supported, not enabled.
       > GC:            sgen

it should refer to https://github.com/mono/docker/blob/master/4.2.1.102/Dockerfile

**Comment by mausch** [comment]
This seems to be fixed now but the same issue applies to `mono:4`, which for some reason is not even listed anymore.

**Comment by akoeplinger** [comment]
These issues should be fixed once https://github.com/docker-library/official-images/pull/1208 is merged. Thanks.

**Comment by akoeplinger** [comment]
This is fixed now. Remove your cached local image via `docker rmi mono:4` and pull again to get the updated image.
