### ISSUE TITLE
Non working on 4.6?

### ISSUE THREAD

**Issue by trycoon** [mono/docker#25]
Got my console WCF application working in mono-docker when running .net 4.5 in my application.
But now that I have switched to 4.6 I get this error when building the image (docker build -t xxx .):

/usr/lib/mono/4.5/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.6'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.

Should I provide any additional parameters to the build to specify that we should compile using .net 4.6?

**Comment by akoeplinger** [comment]
The .NET 4.6 profile isn't supported in the current stable Mono 4.2. It'll be in the next release.
