### ISSUE TITLE
cannot build dockerfile

### ISSUE THREAD

**Issue by RiahiKarim** [mono/docker#29]
When i try to build my dockerfile i have the folowing error :
`/usr/src/app/source/api.sln (default targets) ->
(Build target) ->
/usr/src/app/source/api/api.csproj (default targets) ->
/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->ces target) ->

         1 Warning(s)0041: Unexpected error writing debug information -- 'The method or operation is not implemented.'
         1 Error(s)

Time Elapsed 00:00:04.5832400
The command '/bin/sh -c xbuild /property:Configuration=Release /property:OutDir=/usr/src/app/build/' returned a non-zero code: 1`

The application that i tyr to run in a container it's  a simple asp.net web api

**Comment by akoeplinger** [comment]
Are you using the Roslyn compiler package (Microsoft.CodeAnalysis.CSharp)? You need to disable debug symbol generation in that case.

**Comment by akoeplinger** [comment]
Closing since I think my answer above should fix the error. Feel free to reopen/comment if that's not true.
