### ISSUE TITLE
Beta and alpha versions

### ISSUE THREAD

**Issue by MihaMarkic** [mono/docker#30]
Hi guys,

Perhaps it might make sense to include beta and alpha builds as well since there are official packages out there.

**Comment by akoeplinger** [comment]
Thanks for the suggestion, we'll keep it in mind.

If you want to test alpha/beta right now, you can remove the snapshot apt repository and readd the alpha/beta repository as shown here: http://www.mono-project.com/docs/getting-started/install/linux/#alpha-update-channel

**Comment by MihaMarkic** [comment]
Sure,did that already. :-)

**Comment by akoeplinger** [comment]
According to the guidance on https://github.com/docker-library/official-images#library-definition-files the alpha/beta releases don't really fit with official images:

> Another common case where the term "supported" is stretched a bit is with release candidates. A release candidate is really just a naming convention for what are expected to be shorter-lived releases, so they are totally acceptable and encouraged. Unlike a release candidate, continuous integration builds which have a fully automated release cycle based on code commits or a regular schedule are not appropriate.

In our case the alpha/beta builds are more on the CI build side than "release candidates" and are updated quite often which would require frequent updates to the official image.

I think it's therefore better to not include alpha/beta here and instead use the normal ways of getting these preview releases on top of a base Debian image. Thanks!
