### ISSUE TITLE
Docker mono not supported for .net version 4.5.2

### ISSUE THREAD

**Issue by arpit-nagar** [mono/docker#31]
I am trying to build my winform application which is on .net version 4.5.2.
It could not found any system libraries.
Is .net version 4.5.2 supported with [docker image mono](https://hub.docker.com/_/mono/)?

**Comment by akoeplinger** [comment]
4.5.2 support is included in the upcoming Mono 4.4 release. Set your project to 4.5 for now (it doesn't make a difference on Mono anyway).

**Comment by arpit-nagar** [comment]
Thanks for your quick response.
