### ISSUE TITLE
can't mount vloume from c: drive

### ISSUE THREAD

**Issue by johnz** [mono/docker#39]
docker run -it --rm -v c:\Projects\:/home/projects/ mono /bin/bash

go to /home/projects/ the folder is empty. it works fine if mount d:\Projects\

I'm using the latest mono container, any ideas?

**Comment by akoeplinger** [comment]
Hey, sorry for the late response. This seems to be a common problem on Docker: https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/2

Closing as this doesn't look specific to the Mono image. Thanks!
