### ISSUE TITLE
Distribution conflict error from apt-get update when installing additional packages

### ISSUE THREAD

**Issue by whereisaaron** [mono/docker#40]
If you run 'apt-get update' in this image (tested in 4.4.0) you get a conflicting distribution error. Appears to be caused by slashes in the mono release name.

`W: Conflicting distribution: http://download.mono-project.com wheezy/snapshots/4.4.0.182 Release (expected wheezy/snapshots but got wheezy)`

If the name can't be fixed. Since we don't actually need to update mono, since we can rebuild or re-pull the container. Could a workaround be to remove mono from the apt sources list?

**Comment by directhex** [comment]
This is a warning, not an error, and it's expected
