### ISSUE TITLE
Docker on CentOS

### ISSUE THREAD

**Issue by VikramBPurohit** [mono/docker#41]
Hi,

Can I use this docker image on CentOS? 

When I am looking into the docker file, it has **aptget** command which is _ubuntu_ specific not _CentOS_.

--Vikram

**Comment by akoeplinger** [comment]
This docker image is based on Debian, correct.

You should be able to use the image from a CentOS docker host just fine (remember that the commands in the Dockerfile are executed inside of the container which in this case runs Debian).
