### ISSUE TITLE
version of nuget needs updating

### ISSUE THREAD

**Issue by ItsVeryWindy** [mono/docker#42]
The version of nuget that is installed with the 4.4.2.11 image is an older version (2.8.7.0). This starts to create issues when using packages that rely on features introduced with nuget 2.12 which is the version mono now supports.

**Comment by akoeplinger** [comment]
At the time when image on Docker Hub was created we didn't have nuget 2.12 in the repositories. If you run `apt-get update && apt-get install nuget` you'll get the updated version right now.

It should be fixed as soon as the next build on Docker Hub happens.

**Comment by akoeplinger** [comment]
This is fixed now in the latest images on Docker Hub, you might need to `docker pull` to get the latest. Thanks!
