### ISSUE TITLE
When can we expect docker image for mono 4.6?

### ISSUE THREAD

**Issue by kuznero** [mono/docker#44]

**Comment by dominikhahn** [comment]
@kuznero created a [PR](https://github.com/mono/docker/pull/45)
you could build and run on your local nodes until merged

**Comment by akoeplinger** [comment]
As soon as https://github.com/docker-library/official-images/pull/2164 is merged and built the update will be available on Docker Hub.

**Comment by akoeplinger** [comment]
4.6 is now available on Docker Hub. Thanks!

**Comment by kuznero** [comment]
Super cool! Thanks!

**Comment by kuznero** [comment]
The size of the image dropped from 700 MB to 400 MB, which sounds very suspicious. And one of my services fail to start with some type initialization exception. Please let me know if you need more details on this one if it won't be too obvious from current message.
