### ISSUE TITLE
New mono:latest docker image does not seem to be well

### ISSUE THREAD

**Issue by kuznero** [mono/docker#46]
The size of the image dropped from 700 MB to 400 MB, which sounds very suspicious. And one of my services fail to start with some type initialization exception. Please let me know if you need more details on this one if it won't be too obvious from current message.

Related to [this](https://github.com/mono/docker/issues/44) issue.

**Comment by kuznero** [comment]
False alarm! Sorry for inconvenience... Though it would still be interesting to learn what made mono image that slimmer?

**Comment by akoeplinger** [comment]
I'm pretty sure this was because of https://github.com/mono/docker/issues/37.
