### ISSUE TITLE
Moving to newer debian

### ISSUE THREAD

**Issue by kevfromireland** [mono/docker#53]
Would you welcome a PR to move to a newer version of debian or is it intentionally locked to the current version? 

My reason for wanting to update is that I'd like to be able to install .NET Core for mixed workloads where I need both `mono` and `dotnet` but Core only supports Debian Jessie

**Comment by akoeplinger** [comment]
We can't do it for the existing versions as that'd probably break people that rely on it being Wheezy.
Maybe for the upcoming (major) version.

@directhex thoughts?

**Comment by directhex** [comment]
Yeah, there's gonna be some big changes to the support matrix in Mono 4.8+1. Definitely not going to be Debian 7 any more.

You're not wrong that it might adversely affect users that expect Wheezy - but I'm not ruling out the idea of changing the base distro either. Comes with some advantages, such as being able to run netcore.

**Comment by akoeplinger** [comment]
Sounds good, let's do it when we roll out those changes.
