### ISSUE TITLE
How does ONBUILD work?

### ISSUE THREAD

**Issue by megamindbrian** [mono/docker#57]
I am looking at the code and I don't see any other references to ONBUILD other than the README file.  How do I build my project from within the container?

**Comment by akoeplinger** [comment]
We removed the ONBUILD images per request from upstream Docker folks as they're deprecating that concept.

Depending on you project you could clone the sources inside the container, or mount a volume from the host.

**Comment by marcosox** [comment]
[The official docker hub image page](https://hub.docker.com/_/mono/?tab=description) still references an `-onbuild` image tag FYI

**Comment by akoeplinger** [comment]
@marcosox thanks, looks like this page is built from a separate repo that I wasn't aware of. Sent https://github.com/docker-library/docs/pull/2147 to fix it.
