### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [mono/docker#59]
I was build mono image on arm64 architecture and successed, So I want to konw that we can support arm64 architecture?

**Comment by akoeplinger** [comment]
Mono already supports ARM64 and we have .deb packages for this architecture as well, but not in a Docker image yet. I'm not quite sure how Docker handles different architectures, do you know?

**Comment by longquan7** [comment]
@akoeplinger That's great, I know that arm64 architecture image in this https://hub.docker.com/u/arm64v8/ , I think you can look at this file to add support for arm64 architecture 
https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by longquan7** [comment]
@akoeplinger I was  build this image change From arm64v8/debian:jessie-slim and success on arm64 system. I found that http://download.mono-project.com/repo/debian/dists/jessie/snapshots/5.0.1.1/main/binary-arm64/ has support arm64. So I think on amd64 architecture and arm64 architecture we can use the same dockerfile

**Comment by yosifkit** [comment]
From the official images perspective we encourage architecture independent Dockerfiles (i.e. it can be built on an arch for that arch).  The [multiple-architectures section](https://github.com/docker-library/official-images/tree/d38a710bf01a9bd51c69d0edee69a73c258bcad4#multiple-architectures) goes into more detail on how to update your library file to add more arches.  It requires using the newer RFC-2822 based format on the library file and many of the images in https://github.com/docker-library/ have updated `generate-stackbrew-library.sh` files as example to change your script.

Let me know if you need any help or have any questions!

**Comment by longquan7** [comment]
@akoeplinger Now this image can already support arm64 architecture ?

**Comment by akoeplinger** [comment]
@longquan7 as soon as the upstream PR to Docker library is merged: https://github.com/docker-library/official-images/pull/3342

**Comment by longquan7** [comment]
@akoeplinger Ok, thanks
