### ISSUE TITLE
ARMv6 support

### ISSUE THREAD

**Issue by fkrull** [mono/docker#64]
It'd be great to have prebuilt images supporting ARMv6; in particular, the CPUs in the original Raspberry Pi and the Pi Zeros. The `debian` are available for their armel architecture which the Pi can run, and the downloads.mono-project.org repository has armel packages. It's simply a matter of building the Dockerfile for the architecture (I tried that and it worked just fine, in fact). I believe this would even fall in the arm32v5 bucket.

I suspect these Pi (Pies?) are the only relevant devices that don't yet support ARMv7. However, they're certainly around and the Zeros in particular have not been superseded.

**Comment by akoeplinger** [comment]
This should be easily doable given we already have the packages on download.mono-project.com

**Comment by fkrull** [comment]
Just as an FYI: Docker on ARM doesn't consider the variant (the v5, v6, v7, v8 part) of the specified architecture, it simply uses the first image in the manifest list: moby/moby#34875. In practice, this means adding an arm32v5 version would always cause that image to be used, even on hardware that could run the arm32v7 version, until that issue is fixed. One can still pick a specific image using the <arch> prefix.

**Comment by akoeplinger** [comment]
Thanks, that sounds like a pretty big problem since using armel everywhere will be much slower. Let's wait until the Docker issue is fixed.

**Comment by akoeplinger** [comment]
We added arm32_v5 as an architecture to the Docker image in https://github.com/mono/docker/commit/62317eb8f14c907ef41e1eafc7dac3ddc11e512d and I verified on my Raspberry Pi 2 that I still get the armhf/arm32v7 image from Docker so it looks like the above issue no longer applies.

@fkrull do you happen to have an arm32v5 system to try and see whether you get the correct package now?

**Comment by akoeplinger** [comment]
Ok thanks, I'll close this issue then and hope Docker fixes their side :)
