### ISSUE TITLE
Access denied to mounted volume through Flask App

### ISSUE THREAD

**Issue by jmgibson71** [mono/docker#67]
I am a newbie to mono, and I am also a newbie to .NET programming, but it is necessary for a project that I am working on.

I am experiencing a problem that is kind of weird--at least to my untrained eye.  I'm using docker mono to run a small app that reads a pst file located on a volume mounted to the container.  

`/usr/sbin/mono exeFile.exe args` 

is controlled with a flask app that calls the mono program as a subprocess

```
def convert(self, pst):
        pst_file = pst['fldr']
        pst_acc_name = pst['acc_name']
        p = subprocess.Popen(['/usr/bin/mono', './tomes_pst_extractor/TomesPst2Mime.exe', pst_file, pst_acc_name],
                             stdout=subprocess.PIPE, bufsize=1, close_fds=self.on_posix)
        q = Queue()
        t = Thread(target=self.enqueue_out, args=(p.stdout, q))
        t.daemon = True
        self.sendMessage(self.get_message_for_sending(2, "Processing: {}".format(os.path.join(self.pst_home, pst_acc_name))))
        t.start()
```

I'm getting this exception:
`Exception: System.UnauthorizedAccessException: Access to the path '/home/tomes/data/pst/ is denied.`

If I `exec` into the container and execute the command from `/bin/bash` the process works flawlessly.

Any thoughts would be appreciated.  Thank you.

**Comment by akoeplinger** [comment]
Hey, sorry for the late reply. This doesn't seem related to Mono to me. You could try creating a file with system tools like `touch` and see if that works to rule out Mono.

**Comment by jmgibson71** [comment]
Hey thanks for the reply.  I couldn’t figure it out. So I ended up setting it up DnD style with mono as the entry point and calling docker run from my controlling script.

[NC_State_Seal PMS 2955]Jeremy M. Gibson
Systems Integration Librarian
NC Dept. of Natural and Cultural Resources
919 807-7356
Jeremy.Gibson@ncdcr.gov<mailto:Jeremy.Gibson@ncdcr.gov%0d>

215 N. Blount St.  |  4603 Mail Service Center | Raleigh, North Carolina 27699

Email correspondence to and from this address is subject to the
North Carolina Public Records Law and may be disclosed to third parties.

**Comment by akoeplinger** [comment]
Ok cool, thanks.
