### ISSUE TITLE
Update base containers to stretch?

### ISSUE THREAD

**Issue by evaryont** [mono/docker#68]
Right now the containers are mostly based on `debian:jessie-slim`. Shouldn't they be updated to Debian 9 (Stretch), `debian:stretch-slim`?

**Comment by akoeplinger** [comment]
We could do that but probably not before a major Mono version bump (changing the base is going is likely going to break someone).

**Comment by jhabdas** [comment]
Is there a planned major? Otherwise it seems apt to keep the containers moving forward in parallel and move active support to Stretch. Agree or disagree?

**Comment by jhabdas** [comment]
Also worth noting, you may be able to work with the resin.io team to get some containers managed by their team, which could help lift the burden and give mono users a chance at getting a maintained version of alpine (requested in #56) at least for ARM.

**Comment by jhabdas** [comment]
Is there a planned major? Otherwise it seems apt to keep the containers moving forward in parallel and move active support to Stretch. Agree or disagree?

You may be able to work with the resin.io team to get some [containers managed by their team](https://github.com/resin-io-library/base-images), which could help lift the burden and give mono users a chance at getting a maintained version of alpine (requested in #56) at least for ARM builds which I see Mono also supports according to DockerHub.

**Comment by jhabdas** [comment]
<blockquote>
We could do that but probably not before a major Mono version bump
<cite>—@akoeplinger</cite>
</blockquote>

Why not simply tag the container with a new version? Mono [already has](https://www.mono-project.com/download/stable/#download-lin-debian) installation instructions for deb9 so why the reservation?

**Comment by jhabdas** [comment]
@evaryont Any luck getting Stretch working? It's not like it's bleeding edge or even unstable, and where docker is concerned, using the same operating system will save gigs down the wire for those who want to reuse layers while incorporating mono into their environments. IMO this isn't the kind of thing you wait for a major version bump to do, or you do do this and you bump the major when it's done.

**Comment by jhabdas** [comment]
@evaryont Any luck getting Stretch working? It's not like it's bleeding edge or even unstable, and where docker is concerned, using the same operating system will save gigs down the wire for those who want to reuse layers while incorporating mono into their environments. IMO this isn't the kind of thing you wait for a major version bump to do, or you do do this and you bump the major with it.

**Comment by directhex** [comment]
Done.
