### ISSUE TITLE
Mono:5.8.0.108 docker image shows older mono

### ISSUE THREAD

**Issue by maximmass** [mono/docker#69]
This seems unexpected. Not sure if it's an issue with the way the image is built or in the mono build itself

> docker run -it mono:**5.8.0.108** mono -V

Mono JIT compiler version **5.4.1.7** (tarball Wed Jan 31 23:11:24 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

**Comment by akoeplinger** [comment]
Hey, we had a brief issue after the 5.8.0.108 build was published where our CDN cached an old copy and this got embedded in some Docker builds.

It has been fixed, can you please try `docker pull mono:5.8.0.108` to refresh your copy of the image?

**Comment by maximmass** [comment]
thanks for fixing this so quick!
