### ISSUE TITLE
"Conflicting distribution" warning when RUN-ning "apt-get update"

### ISSUE THREAD

**Issue by lestephane** [mono/docker#73]
I have the following Dockerfile:
```
RUN apt-get update && apt-get install mono-xsp4
```
When docker build-ing I get the following output
```
Step 1/10 : FROM mono:latest
 ---> 40f00b0faf24
...
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://download.mono-project.com stable-jessie/snapshots/5.10.0.160 InRelease [5872 B]
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [641 kB]
Ign http://deb.debian.org jessie InRelease
Get:4 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:5 http://deb.debian.org jessie Release.gpg [2434 B]
Get:6 http://deb.debian.org jessie Release [148 kB]
Get:7 http://download.mono-project.com stable-jessie/snapshots/5.10.0.160/main amd64 Packages [48.3 kB]
Get:8 http://deb.debian.org jessie-updates/main amd64 Packages [23.1 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 10.1 MB in 38s (265 kB/s)
Reading package lists...
W: Conflicting distribution: http://download.mono-project.com stable-jessie/snapshots/5.10.0.160 InRelease (expected stable-jessie/snapshots but got jessie)
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  mono-xsp4-base
The following NEW packages will be installed:
  mono-xsp4 mono-xsp4-base
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 173 kB of archives.
After this operation, 441 kB of additional disk space will be used.
```
Can somebody explain what this warning means, and whether i can / should get rid of it?
```
W: Conflicting distribution: http://download.mono-project.com stable-jessie/snapshots/5.10.0.160 InRelease (expected stable-jessie/snapshots but got jessie)
```

**Comment by akoeplinger** [comment]
The warning is harmless and can be safely ignored. It's a side-effect of how snapshotting the release works in the management software we're using for the Linux package repository.

Essentially when we make a snapshot for e.g. 5.10.0.160 it copies the current release to a new folder and thus the old name persists.

@directhex should we add a few words to http://www.mono-project.com/docs/getting-started/install/linux/#accessing-older-releases that explains this warning?

**Comment by directhex** [comment]
I'm not opposed to adding a note in the docs

**Comment by akoeplinger** [comment]
@directhex ok, could you please open a PR on the website?

**Comment by aaronfranke** [comment]
Is there any reason you can't just change `bionic` to `bionic/snapshots/whatever`? It would be best to avoid warnings in apt if it's not too hard to do so.

**Comment by directhex** [comment]
The conflict isn't that there are multiple repositories configured, it's that the file InRelease says "i am in a directory called `bionic`" when it's actually in a directory called `bionic/snapshots/whatever`.

It says that because it's literally a point-in-time snapshot of the contents of `bionic` at a given point, complete with the InRelease file as it was at that point.

The repository management software we use, `reprepro`, behaves like this.

I thiiiiiink this is the right bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742281

**Comment by benkauffman** [comment]
Well ... for those of us who don't want to just ignore this problem, we get a failing build when creating a docker image.

<img width="1010" alt="Screen Shot 2019-03-26 at 9 59 39 AM" src="https://user-images.githubusercontent.com/16448205/55017452-fe8b7680-4fad-11e9-9edf-d971b2f95540.png">

This is what my Dockerfile looks like:

<img width="381" alt="Screen Shot 2019-03-26 at 9 59 52 AM" src="https://user-images.githubusercontent.com/16448205/55017498-1a8f1800-4fae-11e9-95ac-79579dbe2baf.png">


Work around looks like this:
<img width="305" alt="Screen Shot 2019-03-26 at 10 00 08 AM" src="https://user-images.githubusercontent.com/16448205/55017537-2f6bab80-4fae-11e9-805b-e19116222c6d.png">


I think that there is a better solution than just "ignore the warning".

**Comment by directhex** [comment]
That's not this issue, it's a change on the Debian side. https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by directhex** [comment]
https://github.com/debuerreotype/docker-debian-artifacts/issues/66 is the issue you want to follow

**Comment by MagicRatz** [comment]
> I have the following Dockerfile:
> 
> ```
> RUN apt-get update && apt-get install mono-xsp4
> ```
> 
> When docker build-ing I get the following output
> 
> ```
> Step 1/10 : FROM mono:latest
>  ---> 40f00b0faf24
> ...
> Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
> Get:2 http://download.mono-project.com stable-jessie/snapshots/5.10.0.160 InRelease [5872 B]
> Get:3 http://security.debian.org jessie/updates/main amd64 Packages [641 kB]
> Ign http://deb.debian.org jessie InRelease
> Get:4 http://deb.debian.org jessie-updates InRelease [145 kB]
> Get:5 http://deb.debian.org jessie Release.gpg [2434 B]
> Get:6 http://deb.debian.org jessie Release [148 kB]
> Get:7 http://download.mono-project.com stable-jessie/snapshots/5.10.0.160/main amd64 Packages [48.3 kB]
> Get:8 http://deb.debian.org jessie-updates/main amd64 Packages [23.1 kB]
> Get:9 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
> Fetched 10.1 MB in 38s (265 kB/s)
> Reading package lists...
> W: Conflicting distribution: http://download.mono-project.com stable-jessie/snapshots/5.10.0.160 InRelease (expected stable-jessie/snapshots but got jessie)
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following extra packages will be installed:
>   mono-xsp4-base
> The following NEW packages will be installed:
>   mono-xsp4 mono-xsp4-base
> 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
> Need to get 173 kB of archives.
> After this operation, 441 kB of additional disk space will be used.
> ```
> 
> Can somebody explain what this warning means, and whether i can / should get rid of it?
> 
> ```
> W: Conflicting distribution: http://download.mono-project.com stable-jessie/snapshots/5.10.0.160 InRelease (expected stable-jessie/snapshots but got jessie)
> ```
