### ISSUE TITLE
 System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=2.12.0.0

### ISSUE THREAD

**Issue by OlegKuzovkov** [mono/docker#77]
Hello guys.

This might be an easy question, but when I am trying to run my GTK applications within mono container, I am getting the following error:

> Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
   --- End of inner exception stack trace ---
  at BridgeApp1.GTK.MainClass.Main (System.String[] args) [0x00001] in <7ee2023b6529425f95384c3724c4af6b>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
   --- End of inner exception stack trace ---
  at BridgeApp1.GTK.MainClass.Main (System.String[] args) [0x00001] in <7ee2023b6529425f95384c3724c4af6b>:0 

Could you please help me to solve that issue?

**Comment by directhex** [comment]
Are you installing gtk-sharp2 packages in your Dockerfile?

**Comment by OlegKuzovkov** [comment]
I am not. I thought that the image itself should be self-contained to run any gtk applications.

**Comment by directhex** [comment]
I'm not sure where "every conceivable dependency should be installed out of the box for everyone" ends, but I don't think including Gtk# in the base image is a good idea

**Comment by akoeplinger** [comment]
We won't include gtk# in the base image to keep the size down, it should be easy to install in your own Dockerfile.
