### ISSUE TITLE
write Dockerfile for implement asp.net framework MVC project with Mono on docker in Linux Container

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [mono/docker#78]
I want to lunch asp.net framework MVC with Mono on Linux platform in Docker container

Did you try it?

I can pull mono and restore packages and build project but I cannot run the project with mono.

The project name is aspnetapp2 for the run on docker, you can right-click on RunDocker.NetFramwork.ps1 and then execute or run by PowerShell.
can you help me?

the orginal issue is on
https://github.com/Hatef-Rostamkhani/asp.net.mvc.mono.dockerfile/issues/1

sample project is on
https://github.com/Hatef-Rostamkhani/asp.net.mvc.mono.dockerfile

FROM mono:latest AS build-env

WORKDIR /app

COPY *.csproj ./

RUN msbuild -t:restore

COPY . .

RUN nuget restore aspnetapp2.csproj -SolutionDirectory ../ -Verbosity normal

RUN msbuild

CMD [ "mono", "aspnetapp2.dll" ]

**Comment by akoeplinger** [comment]
ASP.NET support in Mono is pretty limited. You're probably running into a Mono bug with ASP.NET that is not directly related to Docker.
