### ISSUE TITLE
How do I set my own apikey and nuget feed

### ISSUE THREAD

**Issue by kbdaitch** [mono/docker#8]
I tried doing something like:

```Dockerfile
FROM mono:3.12.0

MAINTAINER Jo Shields <jo.shields@xamarin.com>

RUN mkdir -p /usr/src/app/source /usr/src/app/build
WORKDIR /usr/src/app/source

ONBUILD COPY . /usr/src/app/source
ONBUILD RUN nuget setapikey my-key https://my-feed
ONBUILD RUN nuget restore -NonInteractive
ONBUILD RUN xbuild /property:Configuration=Release /property:OutDir=/usr/src/app/build/
ONBUILD WORKDIR /usr/src/app/build

CMD [ "mono",  "./src/myApp/bin/Debug/myApp.exe", "run" ]
```

But that seems to not work at all. If I use your onbuild directly `FROM mono:3.12-onbuild`, it fails to get my private pacakges. How can I inject a nuget call if I don't wish to include my package sources in my mono project itself.

**Comment by kbdaitch** [comment]
I am new to docker but rereading docs, I get why ONBUILD instructions are not running. I will try running a build off of the created build tomorrow.

**Comment by yosifkit** [comment]
@kbdaitch, `ONBUILD` is for inherited images. If you are just making it for yourself, you can just drop the `ONBUILD` and do `RUN` and `COPY` so that you don't have to build twice.

**Comment by kbdaitch** [comment]
@yosifkit Good point. I am still a rookie at `Dockerfiles` soit took a while to wrap my head around `ONBUILD`.

Cannot wait for this [build-time PR](https://github.com/docker/docker/pull/9176) to be merged. Then I won't need to harcode the `apikey` at all.
